export enum BuffType {
  Strength = "strength",
  Dexterity = "dexterity",
  Vulnerable = "vulnerable",
  Weak = "weak",
  Block = "block",
  Poison = "poison",
  Ritual = "ritual",
  Thorns = "thorns",
  Regeneration = "regeneration",
  Intangible = "intangible",
  Stun = "stun",
  Taunt = "taunt",
  Chi = "chi",
  Meditation = "meditation",
}
